### ISSUE TITLE
unable to create file config.php

### ISSUE THREAD

**Issue by streamcoindev** [alx/CumulusClips#1]
SInce the official cumulusclips forum the register function doesnt work and the search function doesnt work either and o the official github they tend to answer after 10 days maybe you can help me 
im getting this error
Unable to perform database portion of installation. The following error occured: 

Unable to create file via FTP (/files/cc-core/system/config.php)

I already checked permissions i am able to create that file just fine by myself but for somereason the script cumulus uses does not i even gave 777 permissions

**Comment by alx** [comment]
Hi @lanaiscool,

Sorry, I haven't ouch this repository for a few years, and you can consider it as deprecated.

I hope you'll find a solution.

Have an nice day,

Alex
